# <font color="purple"><h3 align="center">Pandas Concatenate Tutorial</h3></font>

## <font color='blue'>Basic Concatenation</font>

In [1]:
import pandas as pd

pakistani_weather = pd.DataFrame({
    "city": ["karachi","lahore","peshawar"],
    "temperature": [32,45,30],
    "humidity": [80, 60, 78]
})
pakistani_weather

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78

In [2]:
us_weather = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68, 65, 75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [3]:
df = pd.concat([pakistani_weather, us_weather])
df

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

## <font color='blue'>Ignore Index</font>

In [4]:
df = pd.concat([pakistani_weather, us_weather], ignore_index=True)
df

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78
3  new york           21        68
4   chicago           14        65
5   orlando           35        75

## <font color='blue'>Concatenation And Keys</font>

In [5]:
df = pd.concat([pakistani_weather, us_weather], keys=["pakistan", "us"])
df

                city  temperature  humidity
pakistan 0   karachi           32        80
         1    lahore           45        60
         2  peshawar           30        78
us       0  new york           21        68
         1   chicago           14        65
         2   orlando           35        75

In [6]:
df.loc["us"]

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [7]:
df.loc["pakistan"]

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78

## <font color='blue'>Concatenation Using Index</font>

In [8]:
temperature_df = pd.DataFrame({
    "city": ["karachi","lahore","peshawar"],
    "temperature": [32,45,30],
}, index=[0,1,2])
temperature_df

       city  temperature
0   karachi           32
1    lahore           45
2  peshawar           30

In [9]:
windspeed_df = pd.DataFrame({
    "city": ["lahore","karachi"],
    "windspeed": [7,12],
}, index=[1,0])
windspeed_df

      city  windspeed
1   lahore          7
0  karachi         12

In [10]:
df = pd.concat([temperature_df,windspeed_df],axis=1)
df

       city  temperature     city  windspeed
0   karachi           32  karachi       12.0
1    lahore           45   lahore        7.0
2  peshawar           30      NaN        NaN

## <font color='blue'>Concatenate dataframe with series</font>

In [11]:
s = pd.Series(["Humid","Dry","Rain"], name="event")
s

0    Humid
1      Dry
2     Rain
Name: event, dtype: object

In [12]:
df = pd.concat([temperature_df,s],axis=1)
df

       city  temperature  event
0   karachi           32  Humid
1    lahore           45    Dry
2  peshawar           30   Rain

In [ ]:
# practice 1: I only use concat function in this cell
df1 = pd.DataFrame({
    "Name": ["John", "Jovana"],
    "Age": ["45", "99"]
})
df2 = pd.DataFrame({
    "Name": ["Ali", "Sara"],
    "Age": ["72", "15"]
})
result = pd.concat([df1,df2])
print(result)

     Name Age
0    John  45
1  Jovana  99
0     Ali  72
1    Sara  15

In [ ]:
# Practice 2: I use the code and but in adding i use ignore index in this code
df1 = pd.DataFrame({
    "Name": ["John", "Jovana"],
    "Age": ["45", "99"]
})
df2 = pd.DataFrame({
    "Name": ["Ali", "Sara"],
    "Age": ["72", "15"]
})
result = pd.concat([df1,df2], ignore_index=True)
print(result)

     Name Age
0    John  45
1  Jovana  99
2     Ali  72
3    Sara  15

In [ ]:
# Practice 3: I use axis 1 to concatenate the table in horizontal form
df1 = pd.DataFrame({
    "Name": ["John", "Jovana"],
    "Age": ["45", "99"]
})
df2 = pd.DataFrame({
    "City": ["Mian Chunnu", "Islamabad"]
})
result = pd.concat([df1,df2], axis= 1)
print(result)

     Name Age         City
0    John  45  Mian Chunnu
1  Jovana  99    Islamabad

In [ ]:
# Practice 4: this practice is for concatenate with series
s1 = pd.Series([10,20,30])
s2 = pd.Series([40,50,60])
result = pd.concat([s1, s2], ignore_index=True)
print(result)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64